### ISSUE TITLE
Unable to run App v2.0 beta 2. Mac ARM64

### ISSUE THREAD

**Issue by marcocebrian** [massCodeIO/massCode#14]
On a clean install, when you try to open it for the first time, this is presented and no window will ever come:

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/eriond/massCode/db.json'
at Object.openSync (node:fs:585:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
at Object.writeFileSync (node:fs:2153:35)
at writeToFile (/Applications/massCode.app/Contents/Resources/app.asar/src/main/services/db/index.js:53:24)
at createDb (/Applications/massCode.app/Contents/Resources/app.asar/src/main/services/db/index.js:45:5)
at Object.<anonymous> (/Applications/massCode.app/Contents/Resources/app.asar/src/main/index.js:19:19)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
```

**The manual workaround is easy, create the folder "massCode" inside your $HOME and the app will launch.**

M1 Max.
Monterey 12.3.1

**Comment by antonreshetov** [comment]
@marcocebrian please try [v2.0.0-beta.3](https://github.com/massCodeIO/massCode/releases/tag/v2.0.0-beta.3)

**Comment by marcocebrian** [comment]
Thanks. Working!MARCO CEBRIÁN MUIÑO Loc: Mumbai ***@***.***, 06:57, "Anton Reshetov" ***@***.***>:
@marcocebrian please try v2.0.0-beta.3
