### ISSUE TITLE
[Bug]: "A JavaScript error occurred in the main process" when Google Drive updated location

### ISSUE THREAD

**Issue by rogerioth** [massCodeIO/massCode#291]
### Describe the bug

While using the official macOS Google Drive app (as the storage of the snippet db), the following error is shown upon startup (not recoverable - clicking "Ok" does nothing, user is required to 'force quit' app).
![image](https://user-images.githubusercontent.com/9361619/194199895-653d93c4-7959-4ec3-b96e-886d68e782c3.png)

Exception:
Uncaught Exception:
Error: EACCES: permission denied, mkdir '/Volumes/GoogleDrive/My Drive/Apps/massCode'
at Object.mkdirSync (node:fs:1334:3)
at Object.module.exports.makeDirSync (/Applications/massCode.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/mkdirs/make-dir.js:23:13)
at Object.createFileSync (/Applications/massCode.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/ensure/file.js:59:45)
at createDb (/Applications/massCode.app/Contents/Resources/app.asar/src/main/services/db/

Attempted to solve it by giving full disk access, but no success.
db.json file is there, mirrored (offline) and intact (no corruptions)

### To reproduce

1. Store db.json on a folder in Google Drive
2. Open it's location with masscode (eg: <GoogleDriveRoot>/Apps/massCode/db.json) (location was actually: /Volumes/GoogleDrive/My Drive/Apps/massCode). Alternatively, can use a temporary USB drive location.
3. Google updated the drive location to (/Users/<current user>/My Drive/Apps/massCode)
4. Previous location were unavailable, and the error above was displayed.
5. Removing the App and reinstalling it did not solve the issue
6. I had to manually 'rm -rf' the local persistence directory at (./Library/Application Support/massCode) in order to fix this.
7. An improved error dialog should be displayed, perhaps with the option to "open storage" elsewhere

### Version

v3.4.1

### OS

macOS Monterey 12.6

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by no-mans** [comment]
had the same issue

**Comment by dividedby-0** [comment]
Same issue here.

**Comment by efrancou** [comment]
Same on Windows using virtual drive. Unable to change it even uninstalling.

**Comment by Amitind** [comment]
On Windows update the new location in the file

`C:\Users\**USERNAME**\AppData\Roaming\massCode\v2\preferences.json`

new location of massCode

```
{
"storagePath": "I:\\massCode",
...
}
```

**Comment by techbrarian** [comment]
The same issue is happening for me on my mac studio. The app won't work at all now.

**Comment by antonreshetov** [comment]
**Closing as outdated.**

This issue was reported against an older version of massCode (v3/v4) that relied on the legacy storage system (`db.json` / SQLite). massCode v5 introduces a completely new architecture based on a markdown vault, and we no longer maintain or fix issues for versions below v5.

If you can still reproduce this on the latest v5 release, please open a new issue with up-to-date reproduction steps. Thanks for your report and for using massCode!
